### ISSUE TITLE
An extremely bad idea...

### ISSUE THREAD

**Issue by RichardD2** [RobKraft/SQLInjectionDetection#1]
Since you have to visit every line of code which executes a SQL query to replace `ExecuteReader`, `ExecuteScalar` and `ExecuteNonQuery` with these custom extension methods, it would be better to update that code to use a properly parameterized query instead.

As you say, this cannot possibly detect all SQL Injection attempts. It will just give people a false sense of security.

If you're looking to simplify the conversion to parameterized queries, it's possible to use interpolated strings for that - for example:

```
public static void SafeSetCommandText(this IDbCommand command, FormattableString commandText)
{
    if (command is null) throw new ArgumentNullException(nameof(command));
    if (commandText is null) throw new ArgumentNullException(nameof(commandText));

#if DEBUG
    if (commandText.ArgumentCount == 0)
    {
        throw new SQLFormattingException($"Parameterless command detected: review for SQL Injection.\n{commandText}");
    }
#endif
    
    int parameterIndex = 0;
    var parameterNames = new object[commandText.ArgumentCount];
    foreach (object parameter in commandText.GetArguments())
    {
        string parameterName = $"@p{parameterIndex}";
        parameterNames[parameterIndex] = parameterName;

        var p = command.CreateParameter();
        p.ParameterName = parameterName;
        p.Value = parameter;
        command.Parameters.Add(p);

        parameterIndex++;
    }

    command.CommandText = string.Format(CultureInfo.InvariantCulture, commandText.Format, parameterNames);
}
```
Usage:
```
using (var command = new SqlCommand("", connection))
{
    command.SafeSetCommandText($"select * from customers where firstname like {nameValue}");
}
```

**Comment by RobKraft** [comment]
Thanks for your input Richard.  I recommend doing both.  Changing the code to use parameters and also implementing this technique.  This technique provides a good fallback for catching SQL Injections for cases that can't support parameters, such as dynamic ORDER BY clauses and dynamic columns entered into the SQL.  Many applications construct SQL dynamically and parameters don't support this.

> 
> columnName = "customers";
> 
> command.SafeSetCommandText($"select * from " columnName " where { like {nameValue}");

Also, it is very easy to implement this.  Global find/replace.  You can implement this for your entire code base in an hour.  Changing all the code to use parameters can take months and also introduce errors.
But you are correct, people need to understand, as I mention in this article, that this is no guarantee to totally protect your application from SQL Injection.
